export const SUPPORTED_LANGUAGES = {
    en: 'English',
    es: 'Español',
    de: 'Deutsch',
    am: 'Amharic',
    ar: 'Arabic',
    eu: 'Basque',
    bn: 'Bengali',
    bg: 'Bulgarian',
    ca: 'Catalan',
    chr: 'Cherokee',
    hr: 'Croatian',
    cs: 'Czech',
    da: 'Danish',
    nl: 'Dutch',
    et: 'Estonian',
    fil: 'Filipino',
    fi: 'Finnish',
    fr: 'French',
    el: 'Greek',
    gu: 'Gujarati',
    iw: 'Hebrew',
    hi: 'Hindi',
    hu: 'Hungarian',
    is: 'Icelandic',
    id: 'Indonesian',
    it: 'Italian',
    ja: 'Japanese',
    kn: 'Kannada',
    ko: 'Korean',
    lv: 'Latvian',
    lt: 'Lithuanian',
    ms: 'Malay',
    ml: 'Malayalam',
    mr: 'Marathi',
    no: 'Norwegian',
    pl: 'Polish',
    pt: 'Portuguese (Portugal)',
    'pt-BR': 'Portuguese (Brazil)',
    ro: 'Romanian',
    ru: 'Russian',
    sr: 'Serbian',
    sk: 'Slovak',
    sl: 'Slovenian',
    sw: 'Swahili',
    sv: 'Swedish',
    ta: 'Tamil',
    te: 'Telugu',
    th: 'Thai',
    tr: 'Turkish',
    ur: 'Urdu',
    uk: 'Ukrainian',
    vi: 'Vietnamese',
    cy: 'Welsh',
    'zh-CN': 'Chinese (PRC)',
    'zh-TW': 'Chinese (Taiwan)'
  };
  
  export const VOICE_FOR_LANGUAGE = {
    en: 'en-GB', // English (UK)
    es: 'es-MX',
    de: 'de-DE',
    am: 'am', // Amharic - suponiendo un código genérico ya que no se especificó
    ar: 'ar',
    eu: 'eu', // Basque - asumiendo genérico
    bn: 'bn',
    bg: 'bg',
    ca: 'ca',
    chr: 'chr', // Cherokee - asumiendo genérico
    hr: 'hr',
    cs: 'cs',
    da: 'da',
    nl: 'nl',
    et: 'et',
    fil: 'fil',
    fi: 'fi',
    fr: 'fr',
    el: 'el',
    gu: 'gu',
    iw: 'iw',
    hi: 'hi',
    hu: 'hu',
    is: 'is',
    id: 'id',
    it: 'it',
    ja: 'ja',
    kn: 'kn',
    ko: 'ko',
    lv: 'lv',
    lt: 'lt',
    ms: 'ms',
    ml: 'ml',
    mr: 'mr',
    no: 'no',
    pl: 'pl',
    pt: 'pt-PT', // Portuguese (Portugal)
    'pt-BR': 'pt-BR', // Portuguese (Brazil)
    ro: 'ro',
    ru: 'ru',
    sr: 'sr',
    sk: 'sk',
    sl: 'sl',
    sw: 'sw',
    sv: 'sv',
    ta: 'ta',
    te: 'te',
    th: 'th',
    tr: 'tr',
    ur: 'ur',
    uk: 'uk',
    vi: 'vi',
    cy: 'cy',
    'zh-CN': 'zh-CN', // Chinese (PRC)
    'zh-TW': 'zh-TW' // Chinese (Taiwan)
  };

export const SectionType =  {
  From : 'from',
  To : 'to'
}

